// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCee6WoOwpznUS7zkj6U4C6QnzIkOerLOs',
    appId: '1:812859646863:web:1de1dda85ecd400d28a1fa',
    messagingSenderId: '812859646863',
    projectId: 'chat-app-ee1',
    authDomain: 'chat-app-ee1.firebaseapp.com',
    storageBucket: 'chat-app-ee1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9fO7YxJYXZKLqbCcWnW80o5quuFmJDfQ',
    appId: '1:812859646863:android:da9802177816087128a1fa',
    messagingSenderId: '812859646863',
    projectId: 'chat-app-ee1',
    storageBucket: 'chat-app-ee1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrAKRoB-TOnlO3StLlgMOzwlxg0dLcBgM',
    appId: '1:812859646863:ios:ae9f36da83d1b7e028a1fa',
    messagingSenderId: '812859646863',
    projectId: 'chat-app-ee1',
    storageBucket: 'chat-app-ee1.appspot.com',
    iosClientId: '812859646863-igqecfehu2bisds75a0q1r7qg2qf3a1b.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrAKRoB-TOnlO3StLlgMOzwlxg0dLcBgM',
    appId: '1:812859646863:ios:ae9f36da83d1b7e028a1fa',
    messagingSenderId: '812859646863',
    projectId: 'chat-app-ee1',
    storageBucket: 'chat-app-ee1.appspot.com',
    iosClientId: '812859646863-igqecfehu2bisds75a0q1r7qg2qf3a1b.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
